export const ROUTES = {
  ABOUT: 'about-us',
  PORTFOLIO: 'portfolio',
  HOME: '/',
  DEVELOPMENT: 'web-development',
  VIDEOGRAPHY: 'videography',
  POLICY: 'privacy-policy',
  Blog: 'blog',
};
export const LINKDATA = {
  ABOUT: 'about-us',
  PORTFOLIO: 'portfolio',
  HOME: '/',
  DEVELOPMENT: 'web-development',
  VIDEOGRAPHY: 'videography',
  POLICY: 'privacy-policy',
  Blog: 'blog',
};
export const LANGUAGES = { UA: 'ua', EN: 'en', DE: 'de' };

export const NAMESPACES = [
  'header',
  'titleHome',
  'feedbackForm',
  'reviewsForm',
  'pixelPerfectBlock',
  'getBusinessSolutions',
  'toggleQuestions',
  'IdeasToReality',
  'notFound',
  'errorGlobal',
  'reviewsList',
  'successContent',
  'brandTransformation',
  'modalFeedback',
  'ideasHome',
  'textAnimation',
  'ideasModal',
  'footer',
  'portfolio',
  'toggleQuestionsWebDev',
  'webHero',
  'stepsToLaunch',
  'effectiveSolutions',
  'webWhyChoose',
  'webPortfolio',
  'OrDevelopment',
  'privacyPolicy',
  'heroVideo',
  'videoFaq',
  'videoWhyChoose',
  'videoPortfolio',
  'BlogCategoryPage',
  'heroBlog',
];

export const FLIPPED_TIME_MS = 15000;
